dist: bionic
sudo: true
language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
addons:
  mariadb: '10.4'
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - pip install -r requirements.txt
before_script:
  - cp settings/.env.example settings/.env
  - sed -i.bak -e "s/DATABASE_URL=.*/DATABASE_URL=mysql:\/\/root:@localhost:3306\/test/g" settings/.env;
  - rm settings/.env.bak
  - grep -R "DATABASE_URL" settings/.env
script:
  - python manage.py test accounts.tests
  - python manage.py test catalogue.tests
notifications:
  email:
    recipients:
      - halbesma@MPA-Garching.MPG.DE
    on_success: change
    on_failure: change
