dist: bionic
sudo: true
language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
addons:
  mariadb: '10.4'
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - pip3 install -r requirements.txt
script:
  - python manage.py test accounts.tests
  - python manage.py test catalogue.tests
notifications:
  email:
    recipients:
      - halbesma@MPA-Garching.MPG.DE
    on_success: change
    on_failure: change
