# Generated by Django 2.1.5 on 2019-02-18 13:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=64)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
