# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobularCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Alternate Name')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Additional comments')),
                ('status', models.IntegerField(choices=[(1, 'To be validated'), (2, 'Accepted'), (3, 'Rejected')], default=1)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('doi', models.CharField(blank=True, max_length=256, null=True)),
                ('ads', models.CharField(blank=True, max_length=256, null=True)),
                ('pub_date', models.DateField(null=True, verbose_name='publication date')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
    ]
