# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='tmp',
            field=models.FloatField(blank=True, help_text=b'Metallicity', null=True, verbose_name=b'[M/H]'),
        ),
    ]
