# Generated by Django 2.0.7 on 2018-11-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='val',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Parameter'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
    ]
