# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_observation_tmp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='tmp',
            new_name='metallicity',
        ),
        migrations.AddField(
            model_name='observation',
            name='L',
            field=models.FloatField(blank=True, help_text='Total luminosity', null=True, verbose_name='Luminosity'),
        ),
        migrations.AddField(
            model_name='observation',
            name='MVt',
            field=models.FloatField(blank=True, help_text='Total V-band magnitude', null=True, verbose_name='MVt'),
        ),
        migrations.AddField(
            model_name='observation',
            name='c',
            field=models.FloatField(blank=True, help_text='King concentration parameter', null=True, verbose_name='Concentration'),
        ),
        migrations.AddField(
            model_name='observation',
            name='dec',
            field=models.FloatField(blank=True, help_text='Declination (J2000) [deg]', null=True, verbose_name='DEC'),
        ),
        migrations.AddField(
            model_name='observation',
            name='dfgc',
            field=models.FloatField(blank=True, help_text='Galactocentric distance [kpc]', null=True, verbose_name='D_GC'),
        ),
        migrations.AddField(
            model_name='observation',
            name='dfs',
            field=models.FloatField(blank=True, help_text='Heliocentric distance [kpc]', null=True, verbose_name='D_sun'),
        ),
        migrations.AddField(
            model_name='observation',
            name='ebv',
            field=models.FloatField(blank=True, help_text='Redenning', null=True, verbose_name='E(B-V)'),
        ),
        migrations.AddField(
            model_name='observation',
            name='ellipticity',
            field=models.FloatField(blank=True, help_text='Ellipticity', null=True, verbose_name='Ellip'),
        ),
        migrations.AddField(
            model_name='observation',
            name='esig_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocity dispersion uncertainty'),
        ),
        migrations.AddField(
            model_name='observation',
            name='ev_r',
            field=models.FloatField(blank=True, null=True, verbose_name='Radial velocity uncertainty'),
        ),
        migrations.AddField(
            model_name='observation',
            name='gallat',
            field=models.FloatField(blank=True, help_text=['b'], null=True, verbose_name='b'),
        ),
        migrations.AddField(
            model_name='observation',
            name='gallon',
            field=models.FloatField(blank=True, help_text=['l'], null=True, verbose_name='l'),
        ),
        migrations.AddField(
            model_name='observation',
            name='muV',
            field=models.FloatField(blank=True, help_text='mag/arcsec^2', null=True, verbose_name='Central surface brightness'),
        ),
        migrations.AddField(
            model_name='observation',
            name='r_c',
            field=models.FloatField(blank=True, help_text='King core radius [arcmin]', null=True, verbose_name='Core radius'),
        ),
        migrations.AddField(
            model_name='observation',
            name='r_h',
            field=models.FloatField(blank=True, help_text='Half-light radius [arcmin]', null=True, verbose_name='Half-light radius'),
        ),
        migrations.AddField(
            model_name='observation',
            name='ra',
            field=models.FloatField(blank=True, help_text='Right Ascesion (J2000) [deg]', null=True, verbose_name='RA'),
        ),
        migrations.AddField(
            model_name='observation',
            name='sig_v',
            field=models.FloatField(blank=True, help_text='Radial velocity dispersion [km/s]', null=True, verbose_name='Velocity dispersion'),
        ),
        migrations.AddField(
            model_name='observation',
            name='v_r',
            field=models.FloatField(blank=True, help_text='Radial velocity [km/s]', null=True, verbose_name='Radial velocity'),
        ),
        migrations.AddField(
            model_name='observation',
            name='x_helio',
            field=models.FloatField(blank=True, help_text='Heliocentric cartesian X component [kpc]', null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='observation',
            name='y_helio',
            field=models.FloatField(blank=True, help_text='Heliocentric cartesian Y component [kpc]', null=True, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='observation',
            name='z_helio',
            field=models.FloatField(blank=True, help_text='Heliocentric cartesian Z component [kpc]', null=True, verbose_name='Z'),
        ),
    ]
