# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20180120_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type of profile')),
                ('profile', jsonfield.fields.JSONField(default=dict, verbose_name='Profile')),
                ('modpars', jsonfield.fields.JSONField(default=dict, verbose_name='Model parameters')),
                ('mtype', models.CharField(blank=True, max_length=256, null=True, verbose_name='Model flavour')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference')),
            ],
        ),
    ]
