# Generated by Django 2.1.5 on 2019-02-18 16:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(blank=True, null=True, path='/static')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobularCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('altname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Alternative Name')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=128, null=True, verbose_name='Value')),
                ('sigma_up', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sigma up')),
                ('sigma_down', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sigma down')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('unit', models.CharField(blank=True, help_text='Must comply with astropy.unit', max_length=64)),
                ('scale', models.FloatField(help_text='Scale by which parameters must be multiplied by')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(blank=True, max_length=256, null=True)),
                ('profile', jsonfield.fields.JSONField(default=dict)),
                ('model_parameters', jsonfield.fields.JSONField(default=dict)),
                ('model_flavour', models.CharField(blank=True, max_length=256, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('compilation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_url', models.URLField(help_text="Please insert the ADS url. All other paramters will automatically be retrieved on save!. For example: 'https://ui.adsabs.harvard.edu/abs/1996AJ....112.1487H'", max_length=256, unique=True, verbose_name='ADS url')),
                ('bib_code', models.CharField(blank=True, max_length=24, null=True, verbose_name='Bibliographic Code [ADS]')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('first_author', models.CharField(blank=True, max_length=128, null=True)),
                ('authors', models.TextField(blank=True, max_length=1024, null=True)),
                ('title', models.TextField(blank=True, max_length=256, null=True)),
                ('journal', models.CharField(blank=True, choices=[('aj', 'Astronomical Journal'), ('actaa', 'Acta Astronomica'), ('araa', 'Annual Review of Astron and Astrophys'), ('apj', 'Astrophysical Journal'), ('apjl', 'Astrophysical Journal: Letters'), ('apjs', 'Astrophysical Journal: Supplement'), ('ao', 'Applied Optics'), ('apss', 'Astrophysics and Space Science'), ('aap', 'Astronomy and Astrophysics'), ('aapr', 'Astronomy and Astrophysics Reviews'), ('aaps', 'Astronomy and Astrophysics), Supplement'), ('azh', 'Astronomicheskii Zhurnal'), ('baas', 'Bulletin of the AAS'), ('caa', 'Chinese Astronomy and Astrophysics'), ('cjaa', 'Chinese Journal of Astronomy and Astrophysics'), ('icarus', 'Icarus'), ('jcap', 'Journal of Cosmology and Astroparticle Physics'), ('jrasc', 'Journal of the RAS of Canada'), ('memras', 'Memoirs of the RAS'), ('mnras', 'Monthly Notices of the RAS'), ('na', 'New Astronomy'), ('nar', 'New Astronomy Review'), ('pra', 'Physical Review A: General Physics'), ('prb', 'Physical Review B: Solid State'), ('prc', 'Physical Review C'), ('prd', 'Physical Review D'), ('pre', 'Physical Review E'), ('prl', 'Physical Review Letters'), ('pasa', 'Publications of the Astron. Soc. of Australia'), ('pasp', 'Publications of the ASP'), ('pasj', 'Publications of the ASJ'), ('rmxaa', 'Revista Mexicana de Astronomia y Astrofisica'), ('qjras', 'Quarterly Journal of the RAS'), ('skytel', 'Sky and Telescope'), ('solphys', 'Solar Physics'), ('sovast', 'Soviet Astronomy'), ('ssr', 'Space Science Reviews'), ('zap', 'Zeitschrift fuer Astrophysik'), ('nat', 'Nature'), ('iaucirc', 'IAU Cirulars'), ('aplett', 'Astrophysics Letters'), ('apspr', 'Astrophysics Space Physics Research'), ('bain', 'Bulletin Astronomical Institute of the Netherlands'), ('fcp', 'Fundamental Cosmic Physics'), ('gca', 'Geochimica Cosmochimica Acta'), ('grl', 'Geophysics Research Letters'), ('jcp', 'Journal of Chemical Physics'), ('jgr', 'Journal of Geophysics Research'), ('jqsrt', 'Journal of Quantitiative Spectroscopy and Radiative Transfer'), ('memsai', 'Mem. Societa Astronomica Italiana'), ('nphysa', 'Nuclear Physics A'), ('physrep', 'Physics Reports'), ('physscr', 'Physica Scripta'), ('planss', 'Planetary Space Science'), ('procspie', 'Proceedings of the SPIE')], max_length=8, null=True)),
                ('doi', models.CharField(blank=True, max_length=32, null=True, verbose_name='DOI')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of publication')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Month of publication')),
                ('volume', models.CharField(blank=True, max_length=8, null=True)),
                ('pages', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
        migrations.AddField(
            model_name='observation',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Parameter'),
        ),
        migrations.AddField(
            model_name='observation',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster'),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
    ]
