# Generated by Django 2.0.7 on 2018-11-21 15:43

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpath', models.FilePathField(blank=True, null=True, path='/static')),
                ('furl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobularCluster',
            fields=[
                ('cname', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('altname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Alternative Name')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField(verbose_name='Value')),
                ('sigup', models.FloatField(blank=True, null=True, verbose_name='Sigma up')),
                ('sigdown', models.FloatField(blank=True, null=True, verbose_name='Sigma down')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('pname', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Parameter')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit', models.CharField(help_text='Must comply with astropy.unit', max_length=256, verbose_name='Unit')),
                ('scale', models.FloatField(help_text='Scale by which parameters must be multiplied by', max_length=256, verbose_name='Scale')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type of profile')),
                ('profile', jsonfield.fields.JSONField(default=dict, verbose_name='Profile')),
                ('modpars', jsonfield.fields.JSONField(default=dict, verbose_name='Model parameters')),
                ('mtype', models.CharField(blank=True, max_length=256, null=True, verbose_name='Model flavour')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('comp', models.CharField(blank=True, max_length=64, null=True, verbose_name='Compilation name')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=256, null=True, unique=True, verbose_name='Reference')),
                ('doi', models.CharField(blank=True, max_length=256, null=True, verbose_name='DOI')),
                ('ads', models.CharField(blank=True, max_length=256, null=True, verbose_name='ADS')),
                ('pub_date', models.DateField(null=True, verbose_name='Publication date')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
        migrations.AddField(
            model_name='observation',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Parameter'),
        ),
        migrations.AddField(
            model_name='observation',
            name='rname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.GlobularCluster'),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='rname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Reference'),
        ),
    ]
