# Generated by Django 2.2.5 on 2019-10-23 12:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='model_flavour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='model_parameters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='x',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='x_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='y',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='y_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
