# Generated by Django 2.2.5 on 2019-10-31 15:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20191023_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='y_sigma_down',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='y_sigma_up',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
