# Generated by Django 2.1.5 on 2019-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190225_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='globularcluster',
            name='references',
            field=models.ManyToManyField(related_name='clusters', to='catalogue.Reference'),
        ),
    ]
