# Generated by Django 2.2.5 on 2019-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20191031_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliary',
            name='path',
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='aux/'),
        ),
    ]
