# Generated by Django 2.1.5 on 2019-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_globularcluster_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globularcluster',
            name='references',
        ),
        migrations.AddField(
            model_name='reference',
            name='clusters',
            field=models.ManyToManyField(related_name='references', to='catalogue.GlobularCluster'),
        ),
    ]
