# Generated by Django 2.2 on 2019-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190329_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliary',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='globularcluster',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['-id']},
        ),
    ]
