# Generated by Django 2.2.4 on 2019-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20190812_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroObjectClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='astroobject',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='astro_objects', to='catalogue.AstroObjectClassification', verbose_name='classification'),
        ),
    ]
