# Generated by Django 2.2.4 on 2019-08-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190812_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliary',
            old_name='cluster',
            new_name='astro_object',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='cluster',
            new_name='astro_object',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cluster',
            new_name='astro_object',
        ),
    ]
