# Generated by Django 2.2.4 on 2019-08-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190812_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astroobject',
            old_name='classification',
            new_name='classifications',
        ),
    ]
