# Generated by Django 2.2.4 on 2019-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190812_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='astro_objects',
            field=models.ManyToManyField(blank=True, related_name='references', to='catalogue.AstroObject'),
        ),
    ]
