# Generated by Django 2.2 on 2019-08-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190812_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='astroobjectclassification',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Abbreviation'),
        ),
    ]
