# Generated by Django 2.2.4 on 2019-08-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_astroobjectclassification_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='astro_objects',
        ),
    ]
