# Generated by Django 2.2.4 on 2019-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20190823_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliary',
            name='path',
            field=models.FilePathField(blank=True, null=True, path='/supaharris/static'),
        ),
    ]
