# Generated by Django 2.2.4 on 2019-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190828_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='DOI'),
        ),
    ]
