#-*- coding: utf-8 -*-

schema = {'RA':  'Right Ascesion (J2000) [deg]',
          'Dec': 'Declination (J2000) [deg]',
          'l':   'Galactic longitude [deg]',
          'b':   'Galactic latittude [deg]',
          'D_sun': 'Heliocentric distance [kpc]',
          'D_GC':  'Galactocentric distance [kpc]',
          'X_helio': 'Heliocentric cartesian X component [kpc]',
          'Y_helio': 'Heliocentric cartesian Y component [kpc]',
          'Z_helio': 'Heliocentric cartesian Z component [kpc]',
          '[M/H]': 'Metallicity',
          'MV_t': 'Total V-band magnitude',
          'Luminosity': 'Total luminosity',
          'E(B-V)': 'Redenning',
          'Ellipticity': 'Ellipticity',
          'V_R': 'Radial velocity [km/s]',
          'sigmaV_R': 'Radial velocity dispersion [km/s]',
          'Concentration': 'King concentration parameter',
          'Core radius': 'King core radius [arcmin]',
          'Half-light radius': 'Half-light radius [arcmin]',
          'Central muV': 'mag/arcsec^2'}
